// examples/apps/react-app/src/pages/Home.tsx
import React, { useState } from "react";
import { Card, Space, Typography, Button } from "@arco-design/web-react";
import "./Home.less";

const Home: React.FC = () => {
  const [count, setCount] = useState(0);

  return (
    <div className="home">
      <Card style={{ width: 600 }} title="React 子应用">
        <Space direction="vertical" size="large" style={{ width: "100%" }}>
          <Typography.Paragraph>
            这是一个 React 子应用，当前计数：{count}
          </Typography.Paragraph>
          <Space>
            <Button type="primary" onClick={() => setCount(count + 1)}>
              增加
            </Button>
            <Button status="danger" onClick={() => setCount(count - 1)}>
              减少
            </Button>
          </Space>
        </Space>
      </Card>
    </div>
  );
};

export default Home;

// examples/apps/vue-app/src/views/Home.vue
<template>
  <div class="home">
    <a-card :style="{ width: '600px' }">
      <template #title>Vue 子应用</template>
      <a-space direction="vertical" size="large" fill>
        <a-typography-paragraph>
          这是一个 Vue3 子应用，当前计数：{{ count }}
        </a-typography-paragraph>
        <a-space>
          <a-button type="primary" @click="increment">
            增加
          </a-button>
          <a-button status="danger" @click="decrement">
            减少
          </a-button>
        </a-space>
      </a-space>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);

const increment = () => {
  count.value++;
};

const decrement = () => {
  count.value--;
};
</script>

<style scoped>
.home {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 400px;
}
</style>
